### ISSUE TITLE
Durante o load, os sinais de um Assigner node sempre vêm positivos

### ISSUE THREAD

**Issue by Syndelis** [Syndelis/ode-designer-rs#2]
### Descrição do Problema

Ao carregar um modelo que possua um nó Assigner cuja expressão esteja negativada, é possível perceber que a expressão é carregada positivada ao invés.

### Exemplo em tela

| Antes de Salvar | Depois de Carregar |
| --- | --- |
| ![Image](https://github.com/Syndelis/ode-designer-rs/assets/25804378/94e90f8f-340f-45da-8a0c-cade3b3c404c) | ![Image](https://github.com/Syndelis/ode-designer-rs/assets/25804378/f17cbb38-22c7-4f48-aee3-e79a795fd658) |

---

<details>
<summary>JSON de Exemplo</summary>

```json
{
  "metadata": {
    "name": "TODO",
    "type": "ode",
    "start_time": 0.0,
    "delta_time": 0.0,
    "end_time": 0.0,
    "positions": {
      "a": {
        "x": 185.0,
        "y": 405.0
      },
      "a*-b": {
        "x": 507.0,
        "y": 404.0
      },
      "b": {
        "x": 197.0,
        "y": 578.0
      },
      "da/dt": {
        "x": 690.0,
        "y": 444.0
      }
    }
  },
  "arguments": [
    {
      "name": "b",
      "value": 0.0
    },
    {
      "name": "a*-b",
      "operation": "+",
      "composition": [
        {
          "name": "a",
          "contribution": "+"
        },
        {
          "name": "b",
          "contribution": "+"
        }
      ]
    },
    {
      "name": "a",
      "value": 0.0
    }
  ],
  "equations": [
    {
      "name": "da/dt",
      "operates_on": null,
      "argument": "a*-b",
      "contribution": "-"
    }
  ]
}
```
</details>

**Comment by S-Pz** [comment]
Correção da atribuição do atributo _sign na função new_signed no arquivo pin.rs não estava sendo setado corretamente.
