### ISSUE TITLE
Operações do Expression node são sempre carregadas como soma

### ISSUE THREAD

**Issue by Syndelis** [Syndelis/ode-designer-rs#3]
### Descrição do Problema

Ao carregar qualquer modelo com um nó Expression cuja operação seja `-`, `*` ou `/`, é possível perceber que o operador é carregado como `+`, ao invés do que está definido no JSON.

### Exemplo em tela

| Antes de Salvar | Depois de Carregar |
| --- | --- |
| ![Image](https://github.com/Syndelis/ode-designer-rs/assets/25804378/fda3bb13-aaca-414f-b5fe-12b2668c6566) | ![Image](https://github.com/Syndelis/ode-designer-rs/assets/25804378/08757c5a-0e58-4e0c-8377-3e53cb217f53) |

---

<details>
<summary>Exemplo de JSON</summary>

```json
{
  "metadata": {
    "name": "TODO",
    "type": "ode",
    "start_time": 0.0,
    "delta_time": 0.0,
    "end_time": 0.0,
    "positions": {
      "a": {
        "x": 185.0,
        "y": 405.0
      },
      "a*-b": {
        "x": 507.0,
        "y": 404.0
      },
      "b": {
        "x": 197.0,
        "y": 578.0
      },
      "da/dt": {
        "x": 690.0,
        "y": 444.0
      }
    }
  },
  "arguments": [
    {
      "name": "a*-b",
      "operation": "/",
      "composition": [
        {
          "name": "a",
          "contribution": "+"
        },
        {
          "name": "b",
          "contribution": "+"
        }
      ]
    },
    {
      "name": "a",
      "value": 0.0
    },
    {
      "name": "b",
      "value": 0.0
    }
  ],
  "equations": [
    {
      "name": "da/dt",
      "operates_on": null,
      "argument": "a*-b",
      "contribution": "+"
    }
  ]
}
```
</summary>

**Comment by Diegovsky** [comment]
Resolvido em d1a536eb2e0ab762ba8fbc3cb794617326e9bb83 por mim
